version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
  api:
    depends_on:
      - db
    links:
      - db
    build: 
      context: .
      target: production
    environment:
      - MONGO_HOST="mongodb"
    ports:
      - 3000:3000
