version: "3.8"

services:
  api:
    build:
      context: .
    env_file: .env
    image: piotrostr/plug
    platform: linux/amd64
    depends_on:
      - db
    container_name: api
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=db
  db:
    env_file: .env
    image: mongo
    container_name: db
    ports:
      - 27017:27017
