version: "3.8"
services:
  api:
    depends_on:
      - db
    container_name: api
    image: piotrostr/plug
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=db
  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    # TODO add mounted volue to preserve tokens
