version: "3.8"
services:
  api:
    depends_on:
      - db
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=db
    restart: always
  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    restart: always
