name: CI
on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Start Containers
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Setup Node
        uses: actions/setup-node@master

      - name: Install Deps
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install 

      - name: Run Tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:cov

      - name: Codecov
        uses: codecov/codecov-action@master
        with:
          verbose: true

      - name: Stop Containers
        run: docker-compose -f docker-compose.yml down
