name: CI
on: ["push", "pull_request"]
env:
  API_KEY: ${{ secrets.API_KEY }}
  MONGO_HOST: ${{ secrets.MONGO_HOST }}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master

      - name: Install Deps
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install 

      - name: Run Tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:cov

      - name: Codecov
        uses: codecov/codecov-action@master
        with:
          verbose: true
