name: CI
on: ["push", "pull_request"]
env:
  API_KEY: ${{ secrets.API_KEY }}
  MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
  MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      db:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install Deps
        run: yarn

      - name: Run Tests
        run: yarn test:cov

      - name: Codecov
        uses: codecov/codecov-action@master
        with:
          verbose: true
