name: CI
on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Start Containers
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Setup Node
        uses: actions/setup-node@master

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:cov

      - name: Codecov
        uses: codecov/codecov-action@master
        with:
          verbose: true

      - name: Stop Containers
        run: docker-compose -f docker-compose.yml down
